export type ThemePreset = {
  label: string;
  colors: Record<string, string>;
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    label: "PixShort Cyber-Canvas",
    colors: {
      "--background": "#111318",
      "--foreground": "#e2e2e8",
      "--card": "#1e2024",
      "--card-foreground": "#e2e2e8",
      "--popover": "#1e2024",
      "--popover-foreground": "#e2e2e8",
      "--primary": "#00dbe9",
      "--primary-foreground": "#00363a",
      "--secondary": "#6d11ad",
      "--secondary-foreground": "#d7a4ff",
      "--muted": "#282a2e",
      "--muted-foreground": "#b9cacb",
      "--accent": "#282a2e",
      "--accent-foreground": "#e2e2e8",
      "--destructive": "#93000a",
      "--destructive-foreground": "#ffb4ab",
      "--border": "#3b494b",
      "--input": "#3b494b",
      "--ring": "#849495",
      "--chart-1": "#00f0ff",
      "--chart-2": "#6d11ad",
      "--chart-3": "#2ae500",
      "--chart-4": "#e0b6ff",
      "--chart-5": "#ffb4ab",
      "--sidebar": "#0c0e12",
      "--sidebar-foreground": "#e2e2e8",
      "--sidebar-primary": "#00dbe9",
      "--sidebar-primary-foreground": "#00363a",
      "--sidebar-accent": "#1a1c20",
      "--sidebar-accent-foreground": "#e2e2e8",
      "--sidebar-border": "#3b494b",
      "--sidebar-ring": "#849495",
    },
  },
  {
    label: "Zinc (Default)",
    colors: {
      "--background": "#09090b",
      "--foreground": "#fafafa",
      "--card": "#09090b",
      "--card-foreground": "#fafafa",
      "--popover": "#09090b",
      "--popover-foreground": "#fafafa",
      "--primary": "#fafafa",
      "--primary-foreground": "#18181b",
      "--secondary": "#27272a",
      "--secondary-foreground": "#fafafa",
      "--muted": "#27272a",
      "--muted-foreground": "#a1a1aa",
      "--accent": "#27272a",
      "--accent-foreground": "#fafafa",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#fca5a5",
      "--border": "#27272a",
      "--input": "#27272a",
      "--ring": "#3f3f46",
      "--chart-1": "#3b82f6",
      "--chart-2": "#22c55e",
      "--chart-3": "#eab308",
      "--chart-4": "#a855f7",
      "--chart-5": "#ef4444",
      "--sidebar": "#18181b",
      "--sidebar-foreground": "#fafafa",
      "--sidebar-primary": "#3b82f6",
      "--sidebar-primary-foreground": "#fafafa",
      "--sidebar-accent": "#27272a",
      "--sidebar-accent-foreground": "#fafafa",
      "--sidebar-border": "#27272a",
      "--sidebar-ring": "#3f3f46",
    },
  },
  {
    label: "Ocean Deep",
    colors: {
      "--background": "#0a1628",
      "--foreground": "#e0e7ef",
      "--card": "#0f1f38",
      "--card-foreground": "#e0e7ef",
      "--popover": "#0f1f38",
      "--popover-foreground": "#e0e7ef",
      "--primary": "#38bdf8",
      "--primary-foreground": "#082f49",
      "--secondary": "#1e3a5f",
      "--secondary-foreground": "#bae6fd",
      "--muted": "#172e4a",
      "--muted-foreground": "#94a3b8",
      "--accent": "#172e4a",
      "--accent-foreground": "#e0e7ef",
      "--destructive": "#991b1b",
      "--destructive-foreground": "#fecaca",
      "--border": "#1e3a5f",
      "--input": "#1e3a5f",
      "--ring": "#38bdf8",
      "--chart-1": "#38bdf8",
      "--chart-2": "#818cf8",
      "--chart-3": "#34d399",
      "--chart-4": "#f472b6",
      "--chart-5": "#fb923c",
      "--sidebar": "#071222",
      "--sidebar-foreground": "#e0e7ef",
      "--sidebar-primary": "#38bdf8",
      "--sidebar-primary-foreground": "#082f49",
      "--sidebar-accent": "#0f1f38",
      "--sidebar-accent-foreground": "#e0e7ef",
      "--sidebar-border": "#1e3a5f",
      "--sidebar-ring": "#38bdf8",
    },
  },
  {
    label: "Emerald Night",
    colors: {
      "--background": "#0a1a0f",
      "--foreground": "#e0f0e5",
      "--card": "#0f2416",
      "--card-foreground": "#e0f0e5",
      "--popover": "#0f2416",
      "--popover-foreground": "#e0f0e5",
      "--primary": "#34d399",
      "--primary-foreground": "#052e16",
      "--secondary": "#1a3a25",
      "--secondary-foreground": "#a7f3d0",
      "--muted": "#162e1e",
      "--muted-foreground": "#86a694",
      "--accent": "#162e1e",
      "--accent-foreground": "#e0f0e5",
      "--destructive": "#991b1b",
      "--destructive-foreground": "#fecaca",
      "--border": "#1a3a25",
      "--input": "#1a3a25",
      "--ring": "#34d399",
      "--chart-1": "#34d399",
      "--chart-2": "#a78bfa",
      "--chart-3": "#fbbf24",
      "--chart-4": "#f472b6",
      "--chart-5": "#38bdf8",
      "--sidebar": "#071210",
      "--sidebar-foreground": "#e0f0e5",
      "--sidebar-primary": "#34d399",
      "--sidebar-primary-foreground": "#052e16",
      "--sidebar-accent": "#0f2416",
      "--sidebar-accent-foreground": "#e0f0e5",
      "--sidebar-border": "#1a3a25",
      "--sidebar-ring": "#34d399",
    },
  },
  {
    label: "Violet Haze",
    colors: {
      "--background": "#13091f",
      "--foreground": "#ede5f5",
      "--card": "#1c1030",
      "--card-foreground": "#ede5f5",
      "--popover": "#1c1030",
      "--popover-foreground": "#ede5f5",
      "--primary": "#a78bfa",
      "--primary-foreground": "#1e1033",
      "--secondary": "#2e1a4d",
      "--secondary-foreground": "#ddd6fe",
      "--muted": "#241540",
      "--muted-foreground": "#a090b8",
      "--accent": "#241540",
      "--accent-foreground": "#ede5f5",
      "--destructive": "#991b1b",
      "--destructive-foreground": "#fecaca",
      "--border": "#2e1a4d",
      "--input": "#2e1a4d",
      "--ring": "#a78bfa",
      "--chart-1": "#a78bfa",
      "--chart-2": "#f472b6",
      "--chart-3": "#38bdf8",
      "--chart-4": "#34d399",
      "--chart-5": "#fbbf24",
      "--sidebar": "#0d0618",
      "--sidebar-foreground": "#ede5f5",
      "--sidebar-primary": "#a78bfa",
      "--sidebar-primary-foreground": "#1e1033",
      "--sidebar-accent": "#1c1030",
      "--sidebar-accent-foreground": "#ede5f5",
      "--sidebar-border": "#2e1a4d",
      "--sidebar-ring": "#a78bfa",
    },
  },
];
