/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as Char123LocaleChar125SidebarRouteImport } from './routes/{-$locale}/_sidebar'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as Char123LocaleChar125SidebarIndexRouteImport } from './routes/{-$locale}/_sidebar/index'
import { Route as Char123LocaleChar125SidebarTermsOfServiceRouteImport } from './routes/{-$locale}/_sidebar/terms-of-service'
import { Route as Char123LocaleChar125SidebarPrivacyPolicyRouteImport } from './routes/{-$locale}/_sidebar/privacy-policy'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125SidebarRoute =
  Char123LocaleChar125SidebarRouteImport.update({
    id: '/{-$locale}/_sidebar',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125SidebarIndexRoute =
  Char123LocaleChar125SidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125SidebarRoute,
  } as any)
const Char123LocaleChar125SidebarTermsOfServiceRoute =
  Char123LocaleChar125SidebarTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125SidebarRoute,
  } as any)
const Char123LocaleChar125SidebarPrivacyPolicyRoute =
  Char123LocaleChar125SidebarPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => Char123LocaleChar125SidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/success': typeof AuthSuccessRoute
  '/{-$locale}': typeof Char123LocaleChar125SidebarRouteWithChildren
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125SidebarPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125SidebarTermsOfServiceRoute
  '/{-$locale}/': typeof Char123LocaleChar125SidebarIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/success': typeof AuthSuccessRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125SidebarPrivacyPolicyRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125SidebarTermsOfServiceRoute
  '/{-$locale}': typeof Char123LocaleChar125SidebarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/auth/success': typeof AuthSuccessRoute
  '/{-$locale}/_sidebar': typeof Char123LocaleChar125SidebarRouteWithChildren
  '/{-$locale}/_sidebar/privacy-policy': typeof Char123LocaleChar125SidebarPrivacyPolicyRoute
  '/{-$locale}/_sidebar/terms-of-service': typeof Char123LocaleChar125SidebarTermsOfServiceRoute
  '/{-$locale}/_sidebar/': typeof Char123LocaleChar125SidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/auth/success'
    | '/{-$locale}'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/auth/success'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/sign-in'
    | '/sign-up'
    | '/auth/success'
    | '/{-$locale}/_sidebar'
    | '/{-$locale}/_sidebar/privacy-policy'
    | '/{-$locale}/_sidebar/terms-of-service'
    | '/{-$locale}/_sidebar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  Char123LocaleChar125SidebarRoute: typeof Char123LocaleChar125SidebarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_sidebar': {
      id: '/{-$locale}/_sidebar'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_sidebar/': {
      id: '/{-$locale}/_sidebar/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125SidebarIndexRouteImport
      parentRoute: typeof Char123LocaleChar125SidebarRoute
    }
    '/{-$locale}/_sidebar/terms-of-service': {
      id: '/{-$locale}/_sidebar/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125SidebarTermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125SidebarRoute
    }
    '/{-$locale}/_sidebar/privacy-policy': {
      id: '/{-$locale}/_sidebar/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy'
      preLoaderRoute: typeof Char123LocaleChar125SidebarPrivacyPolicyRouteImport
      parentRoute: typeof Char123LocaleChar125SidebarRoute
    }
  }
}

interface Char123LocaleChar125SidebarRouteChildren {
  Char123LocaleChar125SidebarPrivacyPolicyRoute: typeof Char123LocaleChar125SidebarPrivacyPolicyRoute
  Char123LocaleChar125SidebarTermsOfServiceRoute: typeof Char123LocaleChar125SidebarTermsOfServiceRoute
  Char123LocaleChar125SidebarIndexRoute: typeof Char123LocaleChar125SidebarIndexRoute
}

const Char123LocaleChar125SidebarRouteChildren: Char123LocaleChar125SidebarRouteChildren =
  {
    Char123LocaleChar125SidebarPrivacyPolicyRoute:
      Char123LocaleChar125SidebarPrivacyPolicyRoute,
    Char123LocaleChar125SidebarTermsOfServiceRoute:
      Char123LocaleChar125SidebarTermsOfServiceRoute,
    Char123LocaleChar125SidebarIndexRoute:
      Char123LocaleChar125SidebarIndexRoute,
  }

const Char123LocaleChar125SidebarRouteWithChildren =
  Char123LocaleChar125SidebarRoute._addFileChildren(
    Char123LocaleChar125SidebarRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  Char123LocaleChar125SidebarRoute:
    Char123LocaleChar125SidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
